"""
Email Integration via SendGrid
Sends formatted meeting summary to all participants
"""
import requests
from tenacity import retry, stop_after_attempt, wait_exponential
from config import Config
from logger import get_logger

logger = get_logger("email")

PRIORITY_COLORS = {
    "high": "#e53e3e",
    "medium": "#d69e2e",
    "low": "#38a169"
}


def _build_html(summary: str, action_items: list, decisions: list, organizer_name: str = "", organizer_email: str = "", meeting_url: str = "") -> str:
    # Action items rows
    rows = ""
    for item in action_items:
        color = PRIORITY_COLORS.get(item["priority"].lower(), "#888")
        rows += f"""
        <tr>
            <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0">{item['task']}</td>
            <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0">{item['owner']}</td>
            <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0">{item['deadline']}</td>
            <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0">
                <span style="background:{color};color:white;padding:3px 10px;
                border-radius:12px;font-size:11px;font-weight:bold">
                    {item['priority'].upper()}
                </span>
            </td>
        </tr>"""

    # Decisions list
    decisions_html = ""
    for d in decisions:
        decisions_html += f'<li style="margin:6px 0;color:#4a5568">{d}</li>'

    if not decisions_html:
        decisions_html = '<li style="color:#718096">No formal decisions recorded</li>'

    org_html = ""
    if organizer_name:
        org_contact = f"{organizer_name}"
        if organizer_email:
            org_contact += f" ({organizer_email})"
        org_html = f'<div style="color:rgba(255,255,255,0.9); font-size:13px; margin-top:8px; font-weight:bold;">👤 Organized by: {org_contact}</div>'

    meet_html = ""
    if meeting_url:
        meet_html = f"""
        <!-- Meeting Link -->
        <div style="background:#f7fafc;padding:14px 28px;border:1px solid #e2e8f0;border-top:0;font-size:13px">
            <span style="font-weight:bold;color:#4a5568">🔗 Meeting Link:</span>
            <a href="{meeting_url}" style="color:#0078d4;text-decoration:underline;word-break:break-all">{meeting_url}</a>
        </div>"""

    border_top_style = "0" if meeting_url else "1px solid #e2e8f0"

    return f"""
    <div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;color:#2d3748">

        <!-- Header -->
        <div style="background:linear-gradient(135deg,#0078d4,#005a9e);
                    padding:24px 28px;border-radius:10px 10px 0 0">
            <h2 style="color:white;margin:0;font-size:20px">📋 Meeting Summary</h2>
            {org_html}
            <p style="color:rgba(255,255,255,0.8);margin:6px 0 0;font-size:13px">
                Auto-generated by MeetingActionAgent · Azure AI Foundry + Work IQ
            </p>
        </div>
        {meet_html}

        <!-- Summary -->
        <div style="background:white;padding:24px 28px;border:1px solid #e2e8f0;border-top:{border_top_style}">
            <h3 style="color:#2d3748;margin:0 0 10px;font-size:15px">Summary</h3>
            <p style="color:#4a5568;line-height:1.7;margin:0">{summary}</p>
        </div>

        <!-- Action Items -->
        <div style="background:white;padding:0 28px 24px;border:1px solid #e2e8f0;border-top:0">
            <h3 style="color:#2d3748;font-size:15px;padding-top:20px">Action Items</h3>
            <table style="width:100%;border-collapse:collapse;font-size:13px">
                <tr style="background:#f7fafc">
                    <th style="padding:10px 12px;text-align:left;color:#718096;
                               font-weight:600;border-bottom:2px solid #e2e8f0">Task</th>
                    <th style="padding:10px 12px;text-align:left;color:#718096;
                               font-weight:600;border-bottom:2px solid #e2e8f0">Owner</th>
                    <th style="padding:10px 12px;text-align:left;color:#718096;
                               font-weight:600;border-bottom:2px solid #e2e8f0">Deadline</th>
                    <th style="padding:10px 12px;text-align:left;color:#718096;
                               font-weight:600;border-bottom:2px solid #e2e8f0">Priority</th>
                </tr>
                {rows}
            </table>
        </div>

        <!-- Decisions -->
        <div style="background:#f7fafc;padding:20px 28px;
                    border:1px solid #e2e8f0;border-top:0">
            <h3 style="color:#2d3748;margin:0 0 10px;font-size:15px">Key Decisions</h3>
            <ul style="margin:0;padding-left:20px">{decisions_html}</ul>
        </div>

        <!-- Footer -->
        <div style="background:#2d3748;padding:16px 28px;border-radius:0 0 10px 10px;
                    text-align:center">
            <p style="color:#a0aec0;font-size:12px;margin:0">
                🤖 MeetingActionAgent &nbsp;|&nbsp;
                <a href="https://github.com/Akshatmish/meeting-action-agent"
                   style="color:#63b3ed;text-decoration:none">GitHub</a>
                &nbsp;|&nbsp; Powered by Azure AI Foundry + Work IQ
            </p>
        </div>
    </div>"""


@retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=5))
def send_email(to_email: str, summary: str, action_items: list, decisions: list = [], organizer_name: str = "", organizer_email: str = "", meeting_url: str = ""):
    html = _build_html(summary, action_items, decisions, organizer_name, organizer_email, meeting_url)

    from_name = f"{organizer_name} via MeetingActionAgent" if organizer_name else "MeetingActionAgent"
    payload = {
        "personalizations": [{"to": [{"email": to_email}]}],
        "from": {
            "email": Config.FROM_EMAIL,
            "name": from_name
        },
        "subject": "📋 Meeting Summary & Action Items",
        "content": [{"type": "text/html", "value": html}]
    }

    r = requests.post(
        "https://api.sendgrid.com/v3/mail/send",
        headers={
            "Authorization": f"Bearer {Config.SENDGRID_API_KEY}",
            "Content-Type": "application/json"
        },
        json=payload,
        timeout=10
    )

    if r.status_code == 202:
        logger.info(f"Email sent to {to_email}")
    else:
        logger.error(f"Email error {r.status_code}: {r.text}")
        raise Exception(f"SendGrid failed: {r.status_code}")


def send_all_emails(emails: list, summary: str, action_items: list, decisions: list = [], organizer_name: str = "", organizer_email: str = "", meeting_url: str = ""):
    sent = 0
    for email in emails:
        try:
            send_email(email, summary, action_items, decisions, organizer_name, organizer_email, meeting_url)
            sent += 1
        except Exception as e:
            logger.error(f"Email failed for {email}: {e}")
    logger.info(f"Emails: {sent}/{len(emails)} sent")
